### PR TITLE
add "module" to reservedKeywords

### PR DESCRIPTION
**Pull request by damianrusak**
## Before this PR
Using the word `module` in a type union in Conjure can cause issues - while this isn’t a [reserved](https://www.w3schools.com/js/js_reserved.asp) keyword in JavaScript (the language), it is reserved in the [CommonJS](https://en.wikipedia.org/wiki/CommonJS) module format: 

```
module.exports = {
    helloWorld: "Hello, world!"
};
```

In practice having a symbol named module is likely to cause problems with Webpack. It effectively shadows code generated by Webpack. Here’s an illustration: 

image

## After this PR
`module` is properly "escaped" to `module_` in generated typescript function to construct an object of a type from a union:

`function module_(obj)`

==COMMIT_MSG==
Added the word `module` to `reservedKeywords`.
==COMMIT_MSG==

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/conjure-typescript](https://github.com/palantir/conjure-typescript), @damianrusak! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by damianrusak** [comment]
Hey @fawind would you be able to help with the failing test?

**Comment by iamdanfox** [comment]
@damianrusak https://github.com/palantir/conjure-typescript/blob/develop/CONTRIBUTING.md#development-tips

> When modifying the generated code run RECREATE=true yarn test to automatically regenerate the test cases

**Comment by fawind** [comment]
Unfortunately, this repo is in a grim state at the moment. It still tries to publish to bintray which got shut down a while ago and migrating it to publish to maven central instead is a larger effort as we don't have the tooling for npm repos :(

**Comment by damianrusak** [comment]
@fawind gotcha, is there any path forward you think we could take? This is a bit of a ticking time bomb for us - currently linking locally built typescript api package to a FE repo doesn't work (on runtime webpack throws an error - we do have `module` key in a type union) and depending on the order of how the code is bundled the same might start happening in production too :( having to do a migration of all stored artefacts would be quite costly dev-time-wise for us

**Comment by fawind** [comment]
I spend yesterday trying to migrate this repo to use https://github.com/gradlets/gradle-typescript but ran into multiple blockers and didn't get very far.

I think to unblock this repo we can start with a hacky hybrid approach and just use gradle for [publishing the dist](https://github.com/palantir/conjure-typescript/blob/a144dc92c491aa925026af5491bfd9bc51a93be5/scripts/circle-publish-dist) as the remaining setup (i.e. npm publish) should still work. Can look into this today/tomorrow.

**Comment by fawind** [comment]
Started a PR here: https://github.com/palantir/conjure-typescript/pull/168

**Comment by damianrusak** [comment]
will need https://github.com/palantir/conjure-typescript/pull/168 to make tests pass (scripts are pointing to bintray still, which @fawind is changing in the linked PR)

**Comment by fawind** [comment]
Looks like publishing is flowing again: https://repo1.maven.org/maven2/com/palantir/conjure/typescript/conjure-typescript/4.8.0/

Can you try merging in develop?

**Comment by damianrusak** [comment]
@fawind pushed! fingers crossed :) 
I cannot select the checkbox on changelog bot's comment to generate a changelog, can you please do it instead?

**Comment by fawind** [comment]
How does this affect existing users that have types including the word `union`? Will this be a compile break for them?

**Comment by damianrusak** [comment]
@fawind when conjure-typescript dependency will be updated by the service, the generated typescript api package will differ in such case (the constructor function will be now `Type.module_` instead of `Type.module`) but the network requests done via conjure clients will be unaffected - this will indeed be a compile time break for a typescript consumer, but not a runtime one

**Comment by fawind** [comment]
Hmm, I'm not sure how lax we should be with compile breaks -- although it will probably only affect a few selected consumers. I'll reach out and would like to get a second opinion from someone on the frontend-infra on this.

To double check, what is the current practical implication? You're blocked from using conjure apis that have such types, or only with specific bundling setups?

For reference, this change would result in such API changes:

```diff
  export const IPrimitiveUnion = {
      isModule: isModule,
-     module: module,
+     module_: module_,
      visit: visit
  };

// When calling
- myUnion.module
+ myUnion.module_
```

**Comment by damianrusak** [comment]
eh seems the changelog bot didn't take... ;)

**Comment by fawind** [comment]
Discussed internally and all agree that this is a good change. Currently having a field called `module` can work or fail based on the order of how your code is bundled. Will cut this as a major ref to indicate the potential break however internally, we are mostly clear.

> eh seems the changelog bot didn't take... ;)

Unfortunately, changelog bot doesn't work with forks :(. Will take a look and bring this over the line!

**Review by fawind — APPROVED** [review]

**Comment by ferozco** [comment]
@fawind major versioning conjure-typescript is actually a pretty impactful change since it ends up changing the major version of all of the generated bindings. @patrickszmucer or other FE folks should weigh in on whether this is worth a major rev or not

**Comment by damianrusak** [comment]
@fawind @ferozco happy to take whichever version folks end up deciding for! Indeed in our project the bumb will currently be to `500.x.y`

**Pull request merged**
