### PR TITLE
[improvement] Generate more lenient enums

### LINKED ISSUE #80: Enums should be generated as string constant maps
Right now, Enums are generated as Typescript [string enums](https://www.typescriptlang.org/docs/handbook/enums.html#string-enums).

The problem is that enums of any kind are not assignable to one another, even when they are identical.

```
enum Enum1 {
    Foo = "Foo",
}

enum Enum2 {
    Foo = "Foo",
}

function checkAssignability(value: Enum1): Enum2 {
    return value;
    ~~~~~~~~~~~~~ Type 'Enum1' is not assignable to type 'Enum2'.
}
```

The downside of this is that if you have two versions of the same client library, even if the generated code is identical, their enums cannot interop. What's worse is that enums "poison the well" so to speak, and an enum that exists deep in a nested object type/union hierarchy will make all downstream types unassignable to one another.

The solution is to not use Typescript enums at all. We should instead generate Conjure enums as constant string maps and companion types.

```
type Enum1 = "Foo" | "Bar";
const Enum1 = {
    Foo: "Foo",
    Bar: "Bar",
};

type Enum2 = "Foo" | "Bar";
const Enum2 = {
    Foo: "Foo",
    Bar: "Bar",
};

function checkAssignability(value: Enum1): Enum2 {
    return value; // Valid
}
```

**Does this break runtime compatibility?** No. Both string enums and the above code will have `Enum1.Foo := "Foo"` at runtime.

**But clients generated with the new generator won't interop of clients generated with the old one!** True, but that is the exact problem this fixes going forwards. It is _already the case_ that clients which use enums don't interop with different versions of each other, so this is no worse. After this one interop break, they will play nicely together going forth!

**Why are you bringing in multiple versions of the same client?** I'm not, but my dependencies do.

**Can't you fix this with yarn resolutions?** Yes. However yarn resolutions don't propagate downstream, so everyone has to do this for all affected libraries, and frankly its unnecessary given the above solution resolves the issue with no (obvious to me) downsides.

### PR DESCRIPTION
**Pull request by p-szm**
Fixes https://github.com/palantir/conjure-typescript/pull/80

Based on https://github.com/palantir/conjure-typescript/pull/85 (which ended up being reverted) but I used namespaces instead of objects in order to preserve back compatibility.

## Before this PR
We generated TypeScript enums which were difficult to use across library boundaries since equivalent enums could no be assigned to each other. See #80 for more details

## After this PR
We generate a union type and a namespace.

## Notes

I tested the edge case in https://github.com/palantir/conjure-typescript/pull/85#issuecomment-504482860 which caused the original attempt to be reverted and this time everything compiles correctly:

https://www.typescriptlang.org/play?#code/PTAEHkBsBNQYwPbQKYHNkDsCwAoZAPABwQCcAXeBDAZwswFcBbCAGQBEB9AUQDkBVALKgA3rlDjQAMXDhQAXlAAiaeEUAaMRIBCAQQBK8pbr3rN43QC1Diy6ZwBfXLhCgeyAO6UU6bHiKkKDABDRmRqQiC4ZFcuAHVufiFRHAlQAmJyUDIAT0JolWsVRQBuMzT-TJy80GNrYxKy9ICs3OjLOp0LBpxGiopEGgoChWUZbtSmzIHaGv0Ok1KUiUn+qhn2kdtFxz8MiironjiEwUMAa2RshAAzFrybmPjeQUXnMChYACNkAAsggDcAJYIegkXDXegYOBkYEYUDUeifajIMgcBAwAAUERIIQAXKxOM8BAA6AoAHwJJxJlgAlCIdhCoTCqKAUNcgvRIGQAApBHGMNGY-5BSD0aIKcDsKmkmR04Q7Nkcrm8-mC6AYyWExLE4w0144FxuTzfP5AkEkUAAWkojEIgMgYXBkOhsPhiORqIwHixfLxj2l5P9RJ1nTloB2bykQXt1CyCBtdodoEBGGFkEBsARSJRTqZrsY2UkzoAzD7+fiuPgyJhoNQADxHJ6JNRKa4IBCKAB8cojOCAA

### CODE REVIEW

**Comment by ferozco** [comment]
Lets try out the code change in a large internal repo and then we should be good to go

**Comment by p-szm** [comment]
I tested this on one of our conjure generated packages that has a bunch of enums, and it all seems to work.

**Review by ferozco — APPROVED** [review]
Looks good to me

**Comment by tjwilson90** [comment]
This change breaks the generated code for empty enums. Before this change
```
types:
  definitions:
    default-package: "com.palantir.cosmos.generated"
    objects:
      AircraftGeoPointField:
        values: []
```
generated
```
export enum AircraftGeoPointField {
}
```
and after this change it generates
```
export namespace AircraftGeoPointField {
}

export type AircraftGeoPointField = keyof typeof AircraftGeoPointField;
```
which fails to compile with the error
```
> Task :cosmos-api:compileTypeScript FAILED
cosmos-generated/aircraftGeoPointField.ts(4,50): error TS2708: Cannot use namespace 'AircraftGeoPointField' as a value.
cosmos-generated/aircraftGeoPointField.ts(4,50): error TS4081: Exported type alias 'AircraftGeoPointField' has or is using private name 'AircraftGeoPointField'.
```

**Comment by p-szm** [comment]
thanks for spotting @tjwilson90 . I think we can generate this instead for empty enums:

```
export namespace AircraftGeoPointField {
}

export type AircraftGeoPointField = never;
```

I can put up a fix first thing tomorrow morning if you think that works, but I'm also happy to revert in the meantime.

**Comment by p-szm** [comment]
Also, I'm curious - do you actually use empty enums in your typescript code, or was this an API in progress?

**Comment by ferozco** [comment]
@patrickszmucer is `never` the right type here, seems like `never` can be assigned to anything?

**Comment by tjwilson90** [comment]
My conjure api has a lot of redundancy / self similarity and is itself generated (you can imagine Aircraft being one of many different types of objects). I generate a similar search api for all of them. Some of those generated types (like aircraft) don't have any geo point fields, so the corresponding enum is empty.

**Comment by tjwilson90** [comment]
I don't mind waiting until tomorrow. It blocks an autobump which isn't high priority.

**Comment by p-szm** [comment]
@ferozco you're right - seems like `never` is assignable to anything so it would be a bit dangerous to generate it (although I'm not _too_ worried because empty enums should be super rare).

However, I think I found a better solution - we can use `void` instead which can't be instantiated and also can't be assigned to anything else. Typescript folks did something similar to the `window.name` variable which used to be `never` but it was changed to `void` for better type safety - https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/883

**Comment by p-szm** [comment]
Fix here https://github.com/palantir/conjure-typescript/pull/176

**Pull request merged**
